apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: downloader
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: downloader
  replicas: {{ .Values.downloader.replicas }}
  selector:
    matchLabels:
      app: downloader
  template:
    metadata:
      labels:
        app: downloader
    spec:
      containers:
        - name: downloader
          image: "{{ .Values.downloader.image.repository }}:{{ .Values.downloader.image.tag }}"
          imagePullPolicy: {{ .Values.downloader.image.pullPolicy }}
          ports:
            - containerPort: 50051
          env:
            - name: DOWNLOADER_CONFIG_PATH
              value: /app/configs/downloader.toml
          volumeMounts:
            - name: config
              mountPath: /app/configs
              readOnly: true
            - name: tls
              mountPath: /app/configs/tls/ca.crt
              subPath: ca.crt
              readOnly: true
            - name: tls
              mountPath: /app/configs/tls/node.crt
              subPath: tls.crt
              readOnly: true
            - name: tls
              mountPath: /app/configs/tls/node.key
              subPath: tls.key
              readOnly: true
            - name: cookies
              mountPath: /app/cookies
      volumes:
        - name: config
          secret:
            secretName: downloader-config
            items:
              - key: downloader.toml
                path: downloader.toml
        - name: tls
          secret:
            secretName: downloader-tls-secret
  volumeClaimTemplates:
    - metadata:
        name: cookies
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.downloader.cookies.storageClass | default "" }}
        resources:
          requests:
            storage: {{ .Values.downloader.cookies.storage | default "30Mi" }}
