apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: downloader-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: downloader-tls-secret
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - "downloader.{{ .Release.Namespace }}.svc.cluster.local"
