apiVersion: v1
kind: Service
metadata:
  name: yt-pot-provider
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: yt-pot-provider
  ports:
    - port: 4416
      targetPort: 4416
      protocol: TCP
