//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.38

use super::sea_orm_active_enums::ChatType;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "chats")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tg_id: i64,
    pub username: Option<String>,
    pub created_at: TimeDateTimeWithTimeZone,
    pub updated_at: TimeDateTimeWithTimeZone,
    pub chat_type: Option<ChatType>,
    #[sea_orm(has_many)]
    pub chat_config_exclude_domains: HasMany<super::chat_config_exclude_domains::Entity>,
    #[sea_orm(has_one)]
    pub chat_configs: HasOne<super::chat_configs::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
