//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.11
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "chat_configs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tg_id: i64,
    pub cmd_random_enabled: bool,
    pub updated_at: TimeDateTimeWithTimeZone,
    pub link_is_visible: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chats::Entity",
        from = "Column::TgId",
        to = "super::chats::Column::TgId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Chats,
}

impl Related<super::chats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
