//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.11
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "chats")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tg_id: i64,
    pub username: Option<String>,
    pub created_at: TimeDateTimeWithTimeZone,
    pub updated_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        has_one = "super::chat_config_exclude_domains::Entity",
        has_many = "super::chat_config_exclude_domains::Entity"
    )]
    ChatConfigExcludeDomains,
    #[sea_orm(has_one = "super::chat_configs::Entity")]
    ChatConfigs,
}

impl Related<super::chat_config_exclude_domains::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatConfigExcludeDomains.def()
    }
}

impl Related<super::chat_configs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatConfigs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
