//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.38

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "chat_configs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tg_id: i64,
    pub cmd_random_enabled: bool,
    pub updated_at: TimeDateTimeWithTimeZone,
    pub link_is_visible: bool,
    pub language: String,
    #[sea_orm(belongs_to, from = "tg_id", to = "tg_id", on_update = "Cascade", on_delete = "Cascade")]
    pub chats: HasOne<super::chats::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
