//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.38

use super::sea_orm_active_enums::MediaType;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "downloaded_media")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub file_id: String,
    #[sea_orm(unique_key = "idx_downloaded_media_id_domain_type_lang_sections")]
    pub id: String,
    pub display_id: Option<String>,
    #[sea_orm(unique_key = "idx_downloaded_media_id_domain_type_lang_sections")]
    pub domain: Option<String>,
    #[sea_orm(unique_key = "idx_downloaded_media_id_domain_type_lang_sections")]
    pub media_type: MediaType,
    pub created_at: TimeDateTimeWithTimeZone,
    #[sea_orm(unique_key = "idx_downloaded_media_id_domain_type_lang_sections")]
    pub audio_language: Option<String>,
    #[sea_orm(unique_key = "idx_downloaded_media_id_domain_type_lang_sections")]
    pub crop_start_time: Option<i32>,
    #[sea_orm(unique_key = "idx_downloaded_media_id_domain_type_lang_sections")]
    pub crop_end_time: Option<i32>,
}

impl ActiveModelBehavior for ActiveModel {}
