//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.38

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "chat_type")]
pub enum ChatType {
    #[sea_orm(string_value = "private")]
    Private,
    #[sea_orm(string_value = "group")]
    Group,
    #[sea_orm(string_value = "supergroup")]
    Supergroup,
    #[sea_orm(string_value = "channel")]
    Channel,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "media_type")]
pub enum MediaType {
    #[sea_orm(string_value = "video")]
    Video,
    #[sea_orm(string_value = "audio")]
    Audio,
    #[sea_orm(string_value = "photo")]
    Photo,
}
