//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "chat")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub tg_id: i64,
    pub username: Option<String>,
    pub created_at: TimeDateTimeWithTimeZone,
    pub updated_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chat_downloaded_media::Entity")]
    ChatDownloadedMedia,
}

impl Related<super::chat_downloaded_media::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatDownloadedMedia.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
