//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.11

use super::sea_orm_active_enums::MediaType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "downloaded_media")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub file_id: String,
    pub url_or_id: String,
    pub media_type: MediaType,
    pub created_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chat_downloaded_media::Entity")]
    ChatDownloadedMedia,
}

impl Related<super::chat_downloaded_media::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatDownloadedMedia.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
