//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.11
use super::sea_orm_active_enums::MediaType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "downloaded_media")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub file_id: String,
    pub url_or_id: String,
    pub media_type: MediaType,
    pub index_in_playlist: i16,
    pub chat_tg_id: i64,
    pub created_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
