[package]
name = "downloader"
version = "1.4.10"
edition = "2021"
resolver = "2"

[dependencies]
backoff = { version = "0.4", features = ["tokio"], default-features = false }
bytes = { version = "1", default-features = false }
futures-util = { version = "0.3", default-features = false }
lofty = { version = "0.24", default-features = false }
nix = { version = "0.31", features = ["fs", "signal", "process"], default-features = false }
proto = { path = "../proto" }
regex = { version = "1.12", features = ["perf"], default-features = false }
serde = { version = "1.0", features = ["derive"], default-features = false }
serde_json = { version = "1.0", features = ["std"], default-features = false }
snapsave-parser = "1.0.0"
tempfile = { version = "3.9", default-features = false }
thiserror = { version = "2.0", default-features = false }
tokio = { version = "1.36", features = ["rt-multi-thread", "macros", "process", "sync", "fs", "io-util", "time", "signal"], default-features = false }
tokio-stream = { version = "0.1", features = ["net"], default-features = false }
tokio-util = { version = "0.7", features = ["rt"], default-features = false }
toml = { version = "1.0.6", features = ["parse", "serde"], default-features = false }
tonic = { version = "0.14", features = ["transport", "tls-aws-lc"], default-features = false }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", features = ["registry", "fmt", "ansi", "env-filter"], default-features = false }
url = { version = "2.5", features = ["serde"], default-features = false }
