bot:
  image:
    repository: desiders/ytdl_tg_bot
    tag: "5.0.0"
    pullPolicy: Always

postgres:
  storage: 3Gi
  storageClass: ""
  database: api
  owner: admin
  secretName: db
  superuserSecretName: db-superuser

  backup:
    enabled: true
    schedule: "0 3 * * *"

s3:
  enabled: true
  destinationPath: "s3://backups/"
  endpointURL: "http://s3:9000"
  secretName: s3

rustfs:
  enabled: true
  replicas: 1
  storage: 3Gi
  storageClass: ""
  image:
    repository: rustfs/rustfs
    tag: "latest"
    pullPolicy: IfNotPresent
  secretName: s3

telegramBotApi:
  image:
    pullPolicy: IfNotPresent

ytToolkit:
  image:
    repository: ghcr.io/ikiovi/yt-toolkit/info-api
    tag: "v2.0.0"
    pullPolicy: IfNotPresent

migration:
  enabled: false
  runId: ""
  command: up
  image:
    repository: desiders/ytdl_tg_bot.migration
    tag: "1.6.0"
    pullPolicy: IfNotPresent
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  db:
    secretName: db
    host: postgres-rw
    port: "5432"
