bot:
  image:
    repository: desiders/ytdl_tg_bot
    tag: "5.0.0"
    pullPolicy: Always
  cookiesSecretName: bot-cookies

postgres:
  storage: 3Gi
  torageClass: ""
  database: api
  owner: admin
  secretName: db
  superuserSecretName: db-superuser

telegramBotApi:
  image:
    pullPolicy: IfNotPresent

ytToolkit:
  image:
    repository: ghcr.io/ikiovi/yt-toolkit/info-api
    tag: "v2.0.0"
    pullPolicy: IfNotPresent
