mod auth;
mod client;
mod cookie_assignment;
mod download;
mod errors;
mod handle;
mod media_info;
mod recognize;
mod resolve;
mod retry;
mod router;
mod selection;

pub use auth::authenticated_request;
pub use client::{DownloaderServiceTarget, DownloaderTlsConfig};
pub use cookie_assignment::{AssignmentNodeClient, AssignmentNodeHandle, AssignmentNodeHandleError};
pub use download::{download_media, DownloadEvent, DownloadSession};
pub use errors::{DownloadErrorKind, GetMediaInfoErrorKind, RecognizeSongErrorKind, ResolveSourceErrorKind};
pub use handle::{NodeHandle, NodeHandleError};
pub use media_info::get_media_info;
pub use recognize::{recognize_song, RecognizedSong};
pub use resolve::{resolve_drm_free_source, resolve_to_drm_free};
pub use retry::{with_node_failover, NodeAttemptErrorKind, NodeFailoverError};
pub use router::{DownloaderClusterConfig, NodeRouter};
