apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: "{{ .Values.bot.image.repository }}:{{ .Values.bot.image.tag }}"
          imagePullPolicy: {{ .Values.bot.image.pullPolicy }}
          env:
            - name: CONFIG_PATH
              value: /app/configs/config.toml
          volumeMounts:
            - name: config
              mountPath: /app/configs
              readOnly: true
            - name: tls
              mountPath: /app/configs/tls
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: ytdl-bot-config
            items:
              - key: config.toml
                path: config.toml
        - name: tls
          secret:
            secretName: ytdl-tls
