{{- if and .Values.postgres.backup.enabled .Values.s3.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-backup
  namespace: {{ .Release.Namespace }}
spec:
  cluster:
    name: postgres
  schedule: {{ .Values.postgres.backup.schedule | quote }}
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
{{- end }}
