apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
spec:
  instances: 1
  storage:
    size: {{ .Values.postgres.storage }}
    storageClass: {{ .Values.postgres.storageClass | default "" }}
  superuserSecret:
    name: {{ .Values.postgres.superuserSecretName }}
  bootstrap:
    initdb:
      database: {{ .Values.postgres.database }}
      owner: {{ .Values.postgres.owner }}
      secret:
        name: {{ .Values.postgres.secretName }}
  {{- if and .Values.postgres.backup.enabled .Values.s3.enabled }}
  backup:
    barmanObjectStore:
      destinationPath: {{ .Values.s3.destinationPath }}
      endpointURL: {{ .Values.s3.endpointURL }}
      s3Credentials:
        accessKeyId:
          name: {{ .Values.s3.secretName }}
          key: access-key-id
        secretAccessKey:
          name: {{ .Values.s3.secretName }}
          key: secret-access-key
      wal:
        compression: gzip
  {{- end }}
