apiVersion: v1
kind: Service
metadata:
  name: telegram-bot-api
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: telegram-bot-api
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
    - name: file-server
      port: {{ .Values.telegramBotApi.fileServer.port }}
      targetPort: {{ .Values.telegramBotApi.fileServer.port }}
      protocol: TCP
