apiVersion: v1
kind: Service
metadata:
  name: telegram-bot-api
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: telegram-bot-api
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
