apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot-api
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot-api
  template:
    metadata:
      labels:
        app: telegram-bot-api
    spec:
      containers:
        - name: telegram-bot-api
          image: aiogram/telegram-bot-api:latest
          imagePullPolicy: {{ .Values.telegramBotApi.image.pullPolicy }}
          ports:
            - containerPort: 8081
          env:
            - name: TELEGRAM_LOCAL
              value: "1"
            - name: TELEGRAM_WORK_DIR
              value: {{ .Values.telegramBotApi.dataDir | quote }}
            - name: TELEGRAM_API_ID
              valueFrom:
                secretKeyRef:
                  name: telegram-bot-api
                  key: api_id
            - name: TELEGRAM_API_HASH
              valueFrom:
                secretKeyRef:
                  name: telegram-bot-api
                  key: hash
          volumeMounts:
            - name: tgapi-files
              mountPath: {{ .Values.telegramBotApi.dataDir | quote }}
        - name: file-server
          image: "{{ .Values.telegramBotApi.fileServer.image.repository }}:{{ .Values.telegramBotApi.fileServer.image.tag }}"
          imagePullPolicy: {{ .Values.telegramBotApi.fileServer.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.telegramBotApi.fileServer.port }}
          volumeMounts:
            - name: tgapi-files
              mountPath: {{ .Values.telegramBotApi.dataDir | quote }}
            - name: file-server-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
      volumes:
        - name: tgapi-files
          emptyDir: {}
        - name: file-server-config
          configMap:
            name: telegram-bot-api-file-server
