apiVersion: v1
kind: Service
metadata:
  name: yt-toolkit-api
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: yt-toolkit-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
