name: cleanup-caches

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: MyAlbum/purge-cache@v2
        with:
          max-age: 172800
